### ISSUE TITLE
Only first .less file invokes auto save

### ISSUE THREAD

**Issue by sqwear** [Crunch/Crunch-2#28] opened 2015-07-24 17:08 UTC
Yesterday I reported that only one of my imported .less files invokes a auto save. I can confirm that it is still doing this. Please see attached image. I have 2 files linked and only the first one auto save when I edit. The second file does not show up as linked either.

![crunch_novar](https://cloud.githubusercontent.com/assets/1722790/8880200/be1cdae6-31eb-11e5-9982-35d1c2722f83.png)

**Comment by matthew-dean** [comment] 2015-07-26 19:28
What's the content of those files?

**Comment by sqwear** [comment] 2015-07-27 16:05
Very simple... One is 3 or 4 declared variables. The other is some css declarations with those variables in use.

**Comment by matthew-dean** [comment] 2015-07-31 04:07
This looks like a regression bug. I found this was doing the same thing to me today.

**Comment by matthew-dean** [comment] 2015-08-18 19:53
This should be fixed now in beta 3.

**Comment by matthew-dean** [comment] 2015-09-08 21:48
Closing. Reopen if it's still an issue.

**Closed by matthew-dean** 2015-09-08 21:48 UTC
Labels: bug
