### ISSUE TITLE
Crunch not create compiled files

### ISSUE THREAD

**Issue by pavolhudran** [Crunch/Crunch-2#82] opened 2015-10-12 08:33 UTC

**Comment by matthew-dean** [comment] 2015-10-12 14:24
Are you running into issue #45?

**Comment by pavolhudran** [comment] 2015-10-12 14:43
Hi,

no i solve it, but i couldn’t find a way how to delete it, so i delete text :)

Bye

**Comment by matthew-dean** [comment] 2015-10-12 14:44
How did you solve it, and what do you mean, you couldn't find a way to delete it. You mean the .css file?

**Comment by pavolhudran** [comment] 2015-10-12 14:46
I forget how to convert LESS to CSS, so i thought that application didn’t work. I thought it will convert automatically after saving. But before you must set output file. So i set it and it is working.

With deleting i meant, that i couldn’t find how to delete all issue, so i deleted text within.

**Comment by matthew-dean** [comment] 2015-10-12 21:39
Closing as duplicate of #45.

**Closed by matthew-dean** 2015-10-12 21:39 UTC
