### ISSUE TITLE
Wrong characters displayed

### ISSUE THREAD

**Issue by TommyTheBlackbird** [Crunch/Crunch-2#58] opened 2015-09-15 07:34 UTC
Sometimes (not always), some characters are displayed wrong (line numbers, and the begining and end of the comment).

![crunch2_bug_characters](https://cloud.githubusercontent.com/assets/14106278/9870461/55867b5c-5b8c-11e5-8500-1438b41f43dc.png)

**Comment by matthew-dean** [comment] 2015-09-16 15:56
That is weird, to say the least. Although I have seen infrequent font rendering issues myself. This could be either a problem with the font, or a bug being triggered by font settings. The next beta will have a fix (hopefully) for #39, and I wonder if it might address this as well.

**Comment by TommyTheBlackbird** [comment] 2015-09-23 15:13
It seems almost fixed in the new beta 6. Only the first line number still appears as "S", but the rest of line numbers and the comments are now ok.

**Comment by matthew-dean** [comment] 2015-10-06 23:36
Okay, I believe now that this is actually a Chrome bug, introduced in Chrome 40. I don't have the bug report offhand, but Chrome seems to flip out sometimes and show weird artifacts. (Crunch 2 is built on NWJS, which wraps Chromium and Node.js together.) I tried a lot to try to get it to never happen, but didn't succeed. Hopefully a newer version of NWjs may fix it in the future.

**Comment by matthew-dean** [comment] 2015-10-19 20:02
Should be fixed completely in beta 9. The same fix I did for https://github.com/Crunch/Crunch-2/issues/39 should apply to this.

**Comment by sacerro** [comment] 2015-12-23 10:24
In last version 2.0.8-RC.2 the same error.

![image](https://cloud.githubusercontent.com/assets/1681325/11974763/72a63028-a967-11e5-89b0-0e2667720368.png)

On Windows 10 ver. 1511 (SO compilation 10586.39), not Windows preview.

**Comment by matthew-dean** [comment] 2015-12-23 17:30
Drat. I've created an experimental build for Windows that has DirectWrite disabled. Can you see if this resolves the issue for you? https://github.com/Crunch/Crunch-2/releases/tag/v2.0.9-RC.2

**Comment by sacerro** [comment] 2015-12-24 10:59
It's difficult to know beacuase when this error happens. Restarting Crunch "solved" the problem. With this version this error not happened jet

**Comment by matthew-dean** [comment] 2015-12-24 16:55
@sacerro That looks like a side-effect of disabling DirectWrite, for whatever reason, so I don't think that's really going to work.

The previous fix was that Crunch would set text-indent to 0.1px and then reset it to 0px. This would force a redraw of type, which seemed to circumvent the Chrome 41 / Windows DirectWrite bug (whomever is responsible), but I guess not in all situations.

I've done another experimental build with a different hack that redraws text, here: https://github.com/Crunch/Crunch-2/releases/tag/v2.0.10-RC.2

But, if it happens rarely, you are probably right it's hard to verify. My guess is that the next version of NW.js will resolve this, as it's based on Chrome 47. However, that version of nwjs is still in alpha, so it's not stable enough to migrate to yet.

**Comment by sacerro** [comment] 2015-12-25 09:22
With this version font size is perfect, but I cannot confirm the issue is solved because It's seem ramdom issue

**Comment by TommyTheBlackbird** [comment] 2016-02-02 14:46
In my case it seems completly fixed (_Crunch 2.1.0_)

**Comment by matthew-dean** [comment] 2016-02-02 17:50
I haven't seen it crop up again either. Closing.

**Closed by matthew-dean** 2016-02-02 17:50 UTC
Labels: bug, dependency issue
