### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by mbl-at** [Crunch/Crunch-2#126] opened 2015-11-13 10:33 UTC
Every now and then I get this error when trying to save a file:
![crunch2-error](https://cloud.githubusercontent.com/assets/8981484/11144084/b57b6244-8a02-11e5-95dd-4986a93abcec.png)

**Comment by Pantyboy** [comment] 2015-11-13 16:07
This has been reported in [#124](https://github.com/Crunch/Crunch-2/issues/124).

Regards
Pb

**Comment by matthew-dean** [comment] 2015-11-13 18:27
Closing as duplicate of #124.

**Closed by matthew-dean** 2015-11-13 18:27 UTC
