### ISSUE TITLE
Edit file error

### ISSUE THREAD

**Issue by datdotnet** [Crunch/Crunch-2#157] opened 2016-01-27 08:52 UTC
I edit a html file and there is an error: type error: Can not read the property root of undefind -- oops ....
How to fix it?

**Comment by matthew-dean** [comment] 2016-01-28 21:45
I believe this may be a duplicate of #156, where opening a file or creating one, while in Crunchable view, causes a TypeError. Were you in Crunchable View (tab flipped over)?

**Comment by matthew-dean** [comment] 2016-02-04 21:59
This is fixed in 2.1.1.

**Closed by matthew-dean** 2016-02-04 21:59 UTC
