### ISSUE TITLE
Linux Mint. There's no program in the menu

### ISSUE THREAD

**Issue by OrionBetel** [Crunch/Crunch-2#176] opened 2016-09-08 16:45 UTC
Linux Mint 17.3 Cinnamon 32-bit.
It looks like everything works fine but I can't find the program in the menu "Applications".
However I can launch it in the "../opt/Crunch2" folder.
It'd be nice to fix it.

**Comment by matthew-dean** [comment] 2016-09-30 17:38
Possible dupe of #56?

**Closed** 2017-05-20 12:19 UTC
