### ISSUE TITLE
Losing part of the first character of a line

### ISSUE THREAD

**Issue by Pantyboy** [Crunch/Crunch-2#49] opened 2015-09-05 17:37 UTC
This happens when the line numbers hit double figures. Although it seems start at line number 11, which may have something to do with the first line number appearing to be a letter "S".

![crunch-line-numbers](https://cloud.githubusercontent.com/assets/6214205/9700454/28985400-53fb-11e5-85eb-37b38e29620f.jpg)

![crunch-line-numbers-s](https://cloud.githubusercontent.com/assets/6214205/9700494/1858ac82-53fd-11e5-9329-69dee6a29f48.jpg)

**Comment by matthew-dean** [comment] 2015-09-06 16:58
Good news! I found the cause of this one, so that fix will be in the next beta release.

**Comment by matthew-dean** [comment] 2015-09-08 21:43
Will ship in beta 7.

**Closed** 2015-09-08 21:43 UTC
Labels: bug
