### ISSUE TITLE
Autocomplete Less Functions or CSS

### ISSUE THREAD

**Issue by sacerro** [Crunch/Crunch-2#101] opened 2015-10-26 11:02 UTC
For example: if you are using width property it should show avaible options for this property:

width: auto|value|initial|inherit

This feature would be great for new developers

For mixins it should show params

**Comment by matthew-dean** [comment] 2015-10-26 16:02
Do you know you filed this same issue on Sep 7? Closing as duplicate of #54.

**Closed by matthew-dean** 2015-10-26 16:02 UTC

**Comment by sacerro** [comment] 2015-10-26 17:05
oh! Sorry. I think this issue was solved in beta 9 (or beta 10, don't remember).
