### ISSUE TITLE
Can't install crunch2 - Ubuntu 14.04

### ISSUE THREAD

**Issue by Harukero** [Crunch/Crunch-2#56] opened 2015-09-11 07:48 UTC
I can't install Crunch 2 on Ubuntu 14.04 using the .deb file.

Here is the error :

/usr/share/applications/crunch2.desktop: error: value "Development;Utilities;" for key "Categories" in group "Desktop Entry" contains an unregistered value "Utilities"; values extending the format should start with "X-"
Error on file "/opt/Crunch2/crunch2.desktop": Failed to validate the created desktop file

There is also a warning :
/usr/share/applications/crunch2.desktop: warning: value "Crunch 2" for key "Comment" in group "Desktop Entry" looks redundant with value "Crunch 2" of key "Name"

**Comment by matthew-dean** [comment] 2015-09-11 16:47
@Harukero - Are you in the beta testers group on Facebook? ( https://www.facebook.com/groups/crunchtesters/ )

Linux builds haven't had as much love as Windows / Mac. To be honest, I haven't yet set up a virtual machine to even test them. I was hoping I could get some users to work with first on getting feedback on how well it integrates on Linux. So, if you can join the group, I can maybe get you some development to try to fix any blocking issues to installing / running.

**Comment by amatecha** [comment] 2015-09-11 18:50
Ahh, based on that error, it seems like the .desktop file being generated isn't quite matching the spec for the file format (using unexpected "Categories" values and such).  I'm not familiar with .desktop files but I can easily assume it's like an application shortcut in Linux.  I wonder if the file format has changed in the most recent version(s) of Ubuntu / Debian?

BTW, a simple fix might be to just drop "Utilties" from the Categories for the time being, if a more solid solution can't be easily worked out :)

**Comment by Harukero** [comment] 2015-09-14 07:07
@matthew-dean : I'm not in the group yet. I just sent a request a few minutes ago.
@amatecha : here is the list of possible categories accepted by the validating tool :
http://cgit.freedesktop.org/xdg/desktop-file-utils/tree/src/validate.c#n399

**Comment by matthew-dean** [comment] 2015-09-14 17:11
@Harukero What would you feel are the most important categories for Crunch 2 to install under? Is "Utility" an appropriate category along with "Development"?

**Comment by amatecha** [comment] 2015-09-14 17:32
Nice find @Harukero !  That's great.   I'd argue that it should just be in "Development".  If you want greater granularity it could probably go in the "IDE" sub-category, though I'm not sure the syntax to specify that (would you write "IDE" or "Development/IDE"), and I wonder whether it would show under both categories or just the deepest-level one?

**Comment by Harukero** [comment] 2015-09-17 12:11
@matthew-dean I think the same way as @amatecha. "Development", enhanced with "IDE " sub-category would be great. I think it's enought.
For example, here is the Categories entry for Eclipse :
"Categories=Development;IDE;Java;"

**Comment by matthew-dean** [comment] 2015-09-17 18:30
@Harukero Okay I'll change the categories to "Categories=Development;IDE;"

**Comment by matthew-dean** [comment] 2015-10-05 01:58
Fixed in beta 6

**Comment by hwnder** [comment] 2016-08-15 02:27
This is still an **issue** when installing on Linux systems.

You need to modify the `crunch2.desktop` file to properly execute from the applications menu.

You can easily fix this via the terminal:

```
$ sudo vi /usr/share/applications/crunch2.desktop
```

Now, remove the `Comment` and modify the **`Exec`** parameter as follows:

```
[Desktop Entry]
Version=1.0
Type=Application
Name=Crunch 2
Icon=/opt/Crunch2/icon_256.png
Exec="/opt/Crunch2/Crunch 2"
Categories=Development;IDE;
Terminal=false
X-Desktop-File-Install-Version=0.22
```

**Comment by Artekis** [comment] 2016-08-16 18:01
Yup, I'm getting the same issue.
The only warning is:
/usr/share/applications/crunch2.desktop: warning: value "Crunch 2" for key "Comment" in group "Desktop Entry" looks redundant with value "Crunch 2" of key "Name"

@hwnder I tried that solution, but it didn't work for me. And every time I try to re-run the install, the crunch2.desktop changes back to the original version.

**Comment by matthew-dean** [comment] 2016-08-17 02:56
Hmm, so just to clarify, @hwnder you had a fix, but @Artekis it didn't work for you? If you re-installed, that fix would be removed as it copies over new files. So can you confirm it works as a "temporary" fix (until re-install)?

**Comment by hwnder** [comment] 2016-08-17 03:29
Yes it is a temporary fix until re-installed; then you would have to edit the .desktop files once again. The issue is that when installed, the .desktop files have the argument:

```
Exec=/opt/Crunch2/Crunch2
```

And to apply the temporary fix, it has to be edited as:

```
Exec='/opt/Crunch2/Crunch 2'
```

Since the above is the actual path to the installed executable.

**Comment by Artekis** [comment] 2016-08-17 07:14
@matthew-dean Oh I'm new to Crunch; this is is my first time trying to installing it. So I can't check if the fix works since I don't have a working version of it.

**Comment by amatecha** [comment] 2016-08-17 20:19
I wonder if 
Name=Crunch 2
should be
Name="Crunch 2"
?

**Comment by matthew-dean** [comment] 2017-05-22 00:16
This should be fixed with the last release. Re-open if it's still an issue.

**Closed by matthew-dean** 2017-05-22 00:16 UTC
Labels: bug, OS: Linux

**Comment by casperwilkes** [comment] 2018-05-07 23:22
The actual issue seems to be resolved, **But** I had to log out and log back in for the application to show up in my dash. Just in case someone else came here looking for the same issue.
