### ISSUE TITLE
Run Crunch2 from the terminal

### ISSUE THREAD

**Issue by hwnder** [Crunch/Crunch-2#173] opened 2016-08-15 02:39 UTC
I can't seem to execute from the linux terminal when installed, the system wide symbolic link is broken upon installation because of the created path Crunch2 creates. Any issues regarding this?

**Comment by matthew-dean** [comment] 2016-09-30 17:39
I think this is a dupe of #56. I'll try to get a fix out soon.

**Comment by matthew-dean** [comment] 2016-09-30 17:39
Closing as duplicate.

**Closed by matthew-dean** 2016-09-30 17:39 UTC
